-- Synthetic metadata fixtures only; no comic content or network access.
-- Run from repo root with KOReader's htmlparser and LuaSocket in LUA_PATH.
package.path = 'koplugin/tachikindle.koplugin/?.lua;' .. package.path
local ok, adapter = pcall(require, 'adapters/readallcomics')
assert(ok, 'ReadAllComics adapter must load: ' .. tostring(adapter))
local count = 0
local function eq(actual, expected)
    assert(actual == expected, tostring(actual) .. ' ~= ' .. tostring(expected))
end
local function test(name, fn) fn(); count = count + 1; print('ok ' .. name) end
local function source(body)
    return {def = {base_url = 'https://readallcomics.com'}, calls = {}, fetch = function(self, url)
        self.calls[#self.calls + 1] = url
        return body, body == nil and 'HTTP 522' or nil
    end}
end
local listing = [[<ul class="list-story categories"><li><a class="cat-title" href="/category/test/">Test &amp; Friends</a><img class="book-cover" src="//cdn.example/cover.jpg"></li></ul>]]
test('popular uses root URL, absolute links and adjacent next page', function()
    local s = source(listing .. [[<div class="pagination"><a class="page-numbers">Previous</a><span class="page-numbers current">1</span><a class="page-numbers" href="?paged=2">2</a></div>]])
    local rows, err, more = adapter.fetchMangaList(s, 'popular', 1)
    eq(err, nil); eq(#rows, 1); eq(rows[1].title, 'Test & Friends'); eq(rows[1].url, 'https://readallcomics.com/category/test/')
    eq(rows[1].cover, 'https://cdn.example/cover.jpg'); eq(more, true); eq(s.calls[1], s.def.base_url)
end)
test('popular last page has no false next from previous link', function()
    local s = source(listing .. [[<div class="pagination"><a class="page-numbers">1</a><span class="page-numbers current">2</span></div>]])
    local rows, err, more = adapter.fetchMangaList(s, 'popular', 2)
    eq(#rows, 1); eq(err, nil); eq(more, false); eq(s.calls[1], s.def.base_url .. '/?paged=2')
end)
test('search query is encoded and next uses a.next', function()
    local s = source(listing .. '<a class="next" href="?paged=3">Next</a>')
    local rows, err, more = adapter.fetchMangaList(s, 'search', 2, 'A & B')
    eq(#rows, 1); eq(err, nil); eq(more, true)
    eq(s.calls[1], s.def.base_url .. '/?story=A%20%26%20B&s=&type=comic&paged=2')
    adapter.fetchMangaList(s, 'search', 1, '')
    eq(s.calls[2], s.def.base_url .. '/?story=&s=&type=comic')
end)
test('unsupported latest and network errors are explicit', function()
    local s = source(nil)
    local rows, err = adapter.fetchMangaList(s, 'latest', 1)
    eq(rows, nil); assert(err:match('unsupported')); eq(#s.calls, 0)
    rows, err = adapter.fetchMangaList(s, 'popular', 1)
    eq(rows, nil); eq(err, 'HTTP 522')
end)
test('details use first and last strong and preserve description lines', function()
    local s = source([[<div class="description-archive"><h1>Test</h1><p><img src="cover.jpg"></p><div class="b"><p><strong>Adventure</strong></p><p><strong>Ignored</strong></p><p><strong>Writer</strong></p></div><div id="hidden-description">First line.
Second line.</div></div>]])
    local details, err = adapter.fetchMangaDetails(s, '/category/test/')
    eq(err, nil); eq(details.title, 'Test'); eq(details.author, 'Writer'); eq(details.genres[1], 'Adventure')
    eq(details.cover, s.def.base_url .. '/category/test/cover.jpg'); eq(details.description, 'First line.\nSecond line.')
    eq(s.calls[1], s.def.base_url .. '/category/test/')
end)
test('missing detail container is an error', function()
    local details, err = adapter.fetchMangaDetails(source('<html></html>'), '/test/')
    eq(details, nil); assert(err)
end)
test('chapters preserve DOM order, full manga URL and infer year', function()
    local s = source([[<ul class="list-story"><li><a href="/test-002/">Test 002 (2024)</a></li><li><a href="../test-001/">Test 001 (2023)</a></li><li><a href="javascript:nope">Invalid</a></li><li><a href="/annual/">Annual</a></li></ul>]])
    local rows, err = adapter.fetchChapterList(s, '/category/series/test/')
    eq(err, nil); eq(#rows, 3); eq(rows[1].title, 'Test 002 (2024)'); eq(rows[1].date, '2024-01-01')
    eq(rows[2].url, s.def.base_url .. '/category/series/test-001/'); eq(rows[3].date, nil)
    eq(s.calls[1], s.def.base_url .. '/category/series/test/')
end)
test('pages exclude only div#logo descendants, resolve relative src in order', function()
    local pages, err = adapter.parsePages(source(''), [[<body><div id="logo"><a><img src="/logo.jpg"></a></div><img src="first.jpg"><section><img src="//cdn.example/second.jpg"></section><div id="other"><img src="/third.jpg"></div><img src="data:image/gif;base64,x"><img></body>]], 'https://readallcomics.com/issue/')
    eq(err, nil); eq(#pages, 3); eq(pages[1], 'https://readallcomics.com/issue/first.jpg'); eq(pages[2], 'https://cdn.example/second.jpg'); eq(pages[3], 'https://readallcomics.com/third.jpg')
end)
test('challenge and empty reader markup are errors, not empty success', function()
    local body = '<html><head><title>Just a moment...</title></head><body>Enable JavaScript<script src="/cdn-cgi/challenge-platform/x"></script></body></html>'
    local s = source(body)
    for _, action in ipairs({'fetchMangaList', 'fetchMangaDetails', 'fetchChapterList'}) do
        local rows, err = adapter[action](s, action == 'fetchMangaList' and 'popular' or '/test', 1)
        eq(rows, nil); assert(err:match('challenge'))
    end
    local pages, err = adapter.parsePages(s, body, 'https://readallcomics.com/test/')
    eq(pages, nil); assert(err:match('challenge'))
    pages, err = adapter.parsePages(s, '<body><div id="logo"><img src="/logo.jpg"></div></body>', 'https://readallcomics.com/test/')
    eq(pages, nil); assert(err:match('images'))
end)
test('numeric HTML entities decode in metadata and URL attributes', function()
    local s = source([[<ul class="list-story categories"><li><a class="cat-title" href="/test?x=1&#38;y=2">Test&#039;s &#x2014; Story</a></li></ul>]])
    local rows = adapter.fetchMangaList(s, 'popular', 1)
    eq(rows[1].title, 'Test\'s — Story'); eq(rows[1].url, s.def.base_url .. '/test?x=1&y=2')
end)
test('chapter year uses final parentheses, not an earlier edition year', function()
    local rows = adapter.fetchChapterList(source([[<ul class="list-story"><li><a href="/test">Test (2024) (Special)</a></li></ul>]]), '/category/test/')
    eq(rows[1].date, nil)
end)
print('ReadAllComics: ' .. count .. ' tests passed')
